### ISSUE TITLE
refreshSensor -  no JSON body : Restricted Access

### ISSUE THREAD

**Issue by therntier** [nicoduj/homebridge-gogogate2#14]
I receive the following error after running sometime after homebridge starts..

undefined:1
Restricted Access
^

SyntaxError: Unexpected token R in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.optionalCallback [as _callback] (/usr/local/lib/node_modules/homebridge-gogogate2/index.js:535:24)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-gogogate2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-gogogate2/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-gogogate2/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)

**Comment by therntier** [comment]
This doesn't seem to be based on running events.  After a certain time, the plug in crashes.  I don't recall having this issue with an earlier release (I think I previously had 0.0.7)

**Comment by nicoduj** [comment]
Hi, sorry I missed your original message. I didn't run into this issue, but As I may reboot my homebridge often it might not be so significant.

However, The error is happening while refreshing a sensor. can I ask you if you have a wired or wireless sensor ? (and how many doors) ?

And could you launch in debug mode so that I can see the body returned from the JSON hen it happens ?

**Comment by therntier** [comment]
I’ve done some testing...and the error happens even after a period of idle time. I original had 0.0.7 and updated to the latest release. Recently, I deleted The gogogate2 plug in and reinstalled it. It has been running for 2 hours without error. If I don’t get an error for the rest of the day, I will let you know.

**Comment by therntier** [comment]
I should add...thanks for the plug in. If removing and reinstalling fixes the error...I think it’s great. If you ever need someone to test, please let me know. 

To answer your question...it’s a wireless sensor.

**Comment by nicoduj** [comment]
ok, definitely it can also be an unhandled response from the "api" (more webscrapping in reality). so It might be in iddle time also since there is a refresh timer. 
Feel free to launch in debug if you have this error sometimes, so that when it happens I have more information to check. 
You didn't have this in 0.0.7 since there was no temperature /battery handling of wireless sensor and the error occurs there.

**Comment by nicoduj** [comment]
I improved / tried to handle this case, so that you can update and launch without Debug. If it happens again, it should not break your homebridge instance now.

I close the issue, feel free to reopen in case of any trouble

**Comment by nicoduj** [comment]
I reopen since I encountered this today. In fact, it happens when gogoate is powerd off / powered on again, and thus the cookie of auth is not valid anymore.

will have to handle this case :)
